// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh'

export type Locales =
	| 'en'
	| 'zh'
	| 'zh-TW'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	settings: {
		syntax: {
			/**
			 * 语​法
			 */
			name: string
			/**
			 * 记​号​长​什​么​样
			 */
			desc: string
			prefix: {
				/**
				 * 前​缀​词
				 */
				name: string
				/**
				 * 记​号​形​如​ ​`​<​前​缀​>​:​s​u​n​`​。​改​前​缀​会​让​已​经​写​进​笔​记​的​旧​记​号​失​效​，​请​谨​慎
				 */
				desc: string
				/**
				 * 只​能​用​字​母​、​数​字​、​下​划​线​与​连​字​符​，​长​度​ ​1​-​1​6
				 */
				invalid: string
			}
		}
		suggest: {
			/**
			 * 补​全
			 */
			name: string
			/**
			 * 输​入​记​号​的​两​条​路​径​，​反​引​号​一​律​由​插​件​补
			 */
			desc: string
			enabled: {
				/**
				 * 输​入​时​弹​出​候​选
				 */
				name: string
				/**
				 * 敲​前​缀​或​输​入​别​名​时​弹​出​图​标​候​选​，​回​车​整​段​写​入​含​反​引​号​的​记​号​。​关​掉​后​仍​可​用​「​插​入​图​标​」​命​令
				 */
				desc: string
			}
			alias: {
				/**
				 * 输​入​别​名
				 */
				name: string
				/**
				 * 敲​「​别​名​ ​+​ ​冒​号​」​就​能​弹​出​候​选​。​这​个​别​名​只​存​在​于​补​全​里​，​不​会​写​进​文​件
				 */
				desc: string
				/**
				 * 只​能​用​字​母​、​数​字​、​下​划​线​与​连​字​符​，​长​度​ ​1​-​8
				 */
				invalid: string
			}
		}
	}
	ui: {
		/**
		 * 找​不​到​图​标​「​{​n​a​m​e​}​」
		 * @param {unknown} name
		 */
		unresolved: RequiredParams<'name'>
		/**
		 * O​b​s​i​d​i​a​n​ ​内​置
		 */
		sourceBuiltin: string
		/**
		 * C​u​s​t​o​m​ ​I​c​o​n​s
		 */
		sourceCustomIcons: string
		/**
		 * 我​的​ ​S​V​G
		 */
		sourceUserSvg: string
	}
	commands: {
		insertIcon: {
			/**
			 * 插​入​图​标
			 */
			name: string
			/**
			 * 搜​索​图​标​…
			 */
			placeholder: string
		}
		pickIcon: {
			/**
			 * 从​图​标​库​插​入​图​标
			 */
			name: string
			/**
			 * 没​有​启​用​ ​C​u​s​t​o​m​ ​I​c​o​n​s​，​改​用​内​置​的​图​标​搜​索
			 */
			unavailable: string
			/**
			 * 图​标​「​{​i​d​}​」​的​ ​i​d​ ​里​有​冒​号​、​逗​号​或​反​引​号​，​写​不​进​记​号
			 * @param {unknown} id
			 */
			unreferenceable: RequiredParams<'id'>
		}
		reapply: {
			/**
			 * 重​新​渲​染​本​文​档​的​图​标
			 */
			name: string
		}
	}
}

export type TranslationFunctions = {
	settings: {
		syntax: {
			/**
			 * 语法
			 */
			name: () => LocalizedString
			/**
			 * 记号长什么样
			 */
			desc: () => LocalizedString
			prefix: {
				/**
				 * 前缀词
				 */
				name: () => LocalizedString
				/**
				 * 记号形如 `<前缀>:sun`。改前缀会让已经写进笔记的旧记号失效，请谨慎
				 */
				desc: () => LocalizedString
				/**
				 * 只能用字母、数字、下划线与连字符，长度 1-16
				 */
				invalid: () => LocalizedString
			}
		}
		suggest: {
			/**
			 * 补全
			 */
			name: () => LocalizedString
			/**
			 * 输入记号的两条路径，反引号一律由插件补
			 */
			desc: () => LocalizedString
			enabled: {
				/**
				 * 输入时弹出候选
				 */
				name: () => LocalizedString
				/**
				 * 敲前缀或输入别名时弹出图标候选，回车整段写入含反引号的记号。关掉后仍可用「插入图标」命令
				 */
				desc: () => LocalizedString
			}
			alias: {
				/**
				 * 输入别名
				 */
				name: () => LocalizedString
				/**
				 * 敲「别名 + 冒号」就能弹出候选。这个别名只存在于补全里，不会写进文件
				 */
				desc: () => LocalizedString
				/**
				 * 只能用字母、数字、下划线与连字符，长度 1-8
				 */
				invalid: () => LocalizedString
			}
		}
	}
	ui: {
		/**
		 * 找不到图标「{name}」
		 */
		unresolved: (arg: { name: unknown }) => LocalizedString
		/**
		 * Obsidian 内置
		 */
		sourceBuiltin: () => LocalizedString
		/**
		 * Custom Icons
		 */
		sourceCustomIcons: () => LocalizedString
		/**
		 * 我的 SVG
		 */
		sourceUserSvg: () => LocalizedString
	}
	commands: {
		insertIcon: {
			/**
			 * 插入图标
			 */
			name: () => LocalizedString
			/**
			 * 搜索图标…
			 */
			placeholder: () => LocalizedString
		}
		pickIcon: {
			/**
			 * 从图标库插入图标
			 */
			name: () => LocalizedString
			/**
			 * 没有启用 Custom Icons，改用内置的图标搜索
			 */
			unavailable: () => LocalizedString
			/**
			 * 图标「{id}」的 id 里有冒号、逗号或反引号，写不进记号
			 */
			unreferenceable: (arg: { id: unknown }) => LocalizedString
		}
		reapply: {
			/**
			 * 重新渲染本文档的图标
			 */
			name: () => LocalizedString
		}
	}
}

export type Formatters = {}
